Added pins for multiple locations
csesoc/trainee-1-22t3 pull request #4
Opened 2022-11-07 08:01 UTC by sallyysun

2022-11-07 09:18 UTC, munjoonteo requested changes

2022-11-07 09:18 UTC, munjoonteo commented on client/src/components/map/map.jsx
> +  const iconStyle = style
are these meant to do anything ? i can't seem to get them to change to this

2022-11-07 09:19 UTC, munjoonteo requested changes

2022-11-07 09:19 UTC, munjoonteo commented on client/src/App.jsx
>  function App() {
can you change all instances of `function` to use the `const` syntax

2022-12-04 12:55 UTC, sallyysun commented
Made pins look pretty and added marker labels and infoboxes

2022-12-04 13:05 UTC, closed without merging